
include build/make/variables.mk

check:
	$(CPP_COMPILER) \
	$(CPP_SYNTAX_CHECKER) \
	$(CPP_COMPILER_VERSION) \
	$(CPP_COMPILER_INCLUDE_DIR_FLAG)$(HEADER_DIR) \
	$(CPP_SOURCE_DIR)

gpp: check compile run
	./$(BUILD_DIR)$(CPP_OUTPUT_BIN)

run:
	./$(BUILD_DIR)$(CPP_OUTPUT_BIN)
compile: 
	$(CPP_COMPILER) \
	$(CPP_COMPILER_VERSION) \
	$(CPP_COMPILER_INCLUDE_DIR_FLAG)$(HEADER_DIR) \
	$(CPP_COMPILER_OUTPUT_FLAG) \
	$(BUILD_DIR)$(CPP_OUTPUT_BIN) \
	$(CPP_SOURCE_DIR)
	

gdb: check gdb-build gdb-run


gdb-build:
	$(CPP_COMPILER) \
	$(CPP_DBG_BUILD_FLAGS) \
	$(CPP_COMPILER_VERSION) \
	$(CPP_COMPILER_INCLUDE_DIR_FLAG)$(HEADER_DIR) \
	$(CPP_COMPILER_OUTPUT_FLAG) \
	$(BUILD_DIR)$(CPP_OUTPUT_BIN) \
	$(CPP_SOURCE_DIR) 

gdb-run:
	$(GNU_CPP_DBG) ./$(BUILD_DIR)$(CPP_OUTPUT_BIN)

setup:
	$(MKDIR) $(HEADER_DIR) $(BUILD_DIR) $(SOURCE_DIR)

